pars_default = {
    ("EncTable[{}].PrevEnc", "r"),
    ("Motor[{}].pos", "r"),
    ("Motor[{}].idCmd", "r"),
    ("Motor[{}].Ctrl", "r"),
}


pars_StatusGblListCtrl = {
    ("WDTFault", "r"),
    ("PwrOnFault", "r"),
    ("ProjectLoadErr", "r"),
    ("ConfigLoadErr", "r"),
    ("HWChangeErr", "r"),
    ("FileConfigErr", "r"),
    ("Default", "r"),
    ("NoClocks", "r"),
    ("AbortAll", "r"),
    ("BufSizeErr", "r"),
    ("FlashSizeErr", "r"),
    ("CK3WConfigErr", "r"),
    ("CK3WHWChange", "r"),
}


pars_StatusMotorListCtrl = {
    ("AmpEna", "r"),
    ("AmpWarn", "r"),
    ("AmpFault", "r"),
    ("ClosedLoop", "r"),
    ("I2tFault", "r"),
    ("FeWarn", "r"),
    ("FeFatal", "r"),
    ("DesVelZero", "r"),
    ("InPos", "r"),
    ("InPosBand", "rw"),
    ("LimitStop", "r"),
    ("MinusLimit", "r"),
    ("PlusLimit", "r"),
    ("EncLoss", "r"),
    ("HomeInProgress", "r"),
    ("HomeComplete", "r"),
    ("HomeOffset", "r"),
    ("TriggerMove", "r"),
    ("DacLimit", "r"),
    ("SoftLimit", "r"),
    ("SoftMinusLimit", "r"),
    ("SoftPlusLimit", "r"),
    ("SoftLimitDir", "r"),
    ("TriggerNotFound", "r"),
    ("AuxFault", "r"),
    ("BlockRequest", "r"),
    ("PhaseFound", "r"),
    ("TriggerSpeedSel", "r"),
    ("GantryHomed", "r"),
    ("SpindleMotor", "r"),
    ("Csolve", "r"),
    ("Servo.OutDbOn", "rw"),
    ("Servo.OutDbOff", "rw"),
    ("Servo.BreakPosErr", "rw"),
    ("Servo.Kp", "rw"),
    ("Servo.Ki", "rw"),
    ("Servo.Kvff", "rw"),
    ("Servo.Kaff", "rw"),
    ("Servo.Kviff", "rw"),
    ("Servo.MaxPosErr", "rw"),
    ("Servo.MaxInt", "rw"),
    ("FatalFeLimit", "rw"),
    ("WarnFeLimit", "rw"),
    ("BlDir", "r"),
    ("BlDir", "r"),
    ("BlDir", "r"),
    ("BlDir", "r"),
    # ('TraceCount'     , 8,1)))
}


pars_StatusCoordListCtrl = {
    ("TriggerMove", "r"),
    ("HomeInProgress", "r"),
    ("MinusLimit", "r"),
    ("PlusLimit", "r"),
    ("FeWarn", "r"),
    ("FeFatal", "r"),
    ("LimitStop", "r"),
    ("AmpFault", "r"),
    ("SoftMinusLimit", "r"),
    ("SoftPlusLimit", "r"),
    ("I2tFault", "r"),
    ("TriggerNotFound", "r"),
    ("AmpWarn", "r"),
    ("EncLoss", "r"),
    ("AuxFault", "r"),
    ("TimerEnabled", "r"),
    ("HomeComplete", "r"),
    ("DesVelZero", "r"),
    ("ClosedLoop", "r"),
    ("AmpEna", "r"),
    ("InPos", "r"),
    ("InPosBand", "rw"),
    ("ErrorStatus", "r"),
    ("BlockRequest", "r"),
    ("TimersEnabled", "r"),
    ("Csolve", "r"),
    ("LinToPvtBuf", "r"),
    ("FeedHold", "r"),
    ("BlockActive", "r"),
    ("ContMotion", "r"),
    ("CCMode", "r"),
    ("MoveMode", "r"),
    ("SegMove", "r"),
    ("SegMoveAccel", "r"),
    ("SegMoveDecel", "r"),
    ("SegEnabled", "r"),
    ("SegStopReq", "r"),
    ("LookAheadWrap", "r"),
    ("LookAheadLookBack", "r"),
    ("LookAheadDir", "r"),
    ("LookAheadStop", "r"),
    ("LookAheadChange", "r"),
    ("LookAheadReCalc", "r"),
    ("LookAheadFlush", "r"),
    ("LookAheadActive", "r"),
    ("CCAddedArc", "r"),
    ("CCOffReq", "r"),
    ("CCMoveType", "r"),
    ("CC3Active", "r"),
    ("SharpCornerStop", "r"),
    ("AddedDwellDis", "r"),
    #   ('ProgRunning',     'r'),
    #   ('ProgActive',      'r'),
    #   ('ProgProceeding',  'r'),
    #   ('BufferWarn',      'r'))
}

pars_default = {
    ("EncTable[{}].PrevEnc", "r"),
    ("Motor[{}].pos", "r"),
    ("Motor[{}].idCmd", "r"),
    ("Motor[{}].Ctrl", "r"),
}

pars_motors = pars_default.union(
    {("Motor[{}]." + par, mode) for par, mode in pars_StatusMotorListCtrl}
)
