aliases = dict(
        OPSH044 = dict(
            alias = 'ShutUnd'
            z_und = 44
            desc = 'Photon shutter after Undulator'),
        OAPU044 = dict(
            alias = 'SlitUnd'
            z_und = 44
            desc = 'Slit after Undulator'),
        PBIG050 = dict(
            alias = 'GasMon'
            z_und = 50
            desc = 'Gas Monitor Intensity'),
        PBPS053 = dict(
            alias = 'MonUnd'
            z_und = 44
            desc = 'Intensity position monitor after Undulator'),
        OATT053 = dict(
            alias = 'AttFE'
            z_und = 53
            desc = 'Attenuator in Front End'),
        SBST060 = dict(
            alias = 'ShutFE'
            z_und = 60
            desc = 'Photon shutter in the end of Front End'),
        PPRM064 = dict(
            alias = 'ProfFE'
            z_und = 64
            desc = 'Profile monitor after Front End'),
        OOMH064 = dict(
            alias = 'MirrAlv1'
            z_und = 64
            desc = 'Horizontal mirror Alvra 1'),
        PPRM066 = dict(
            alias = 'ProfMirrAlv1'
            z_und = 66
            desc = 'Profile monitor after Alvra Mirror 1'),
        OAPU092 = dict(
            alias = 'SlitSwitch'
            z_und = 92
            desc = 'Slit in Optics hutch after Photon switchyard and before Bernina optics'),
        OOMV092 = dict(
            alias = 'Mirr1'
            z_und = 92
            desc = 'Vertical offset Mirror 1'),
        PPRM094 = dict(
            alias = 'ProfMirr1'
            z_und = 94
            desc = 'Profile monitor after Mirror 1'),
        OOMV096 = dict(
            alias = 'Mirr2'
            z_und = 96
            desc = 'Vertical offset mirror 2'),
        PSCR097 = dict(
            alias = 'ProfMirr2'
            z_und = 097
            desc = 'Profile Monitor after Mirror 2'),
        ODCM098 = dict(
            alias = 'Mono'
            z_und = 98
            desc = 'DCM Monochromator'),
        PPRM102 = dict(
            alias = 'ProfMono'
            z_und = 102
            desc = 'Profile monitor after Monochromator'),
        OPPI103 = dict(
            alias = 'Pick'
            z_und = 103
            desc = 'X-ray pulse picker'),
        BST114 = dict(
            alias = 'ShutOpt'
            z_und = 114
            desc = 'Shutter after Optics hutch'),
        PBPS133 = dict(
            alias = 'MonOpt'
            z_und = 133
            desc = 'Intensity/position monitor after Optics hutch'),
#         = dict(
#            alias = ''
#            z_und = 
#            desc = ''),
      )


